#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hoe-bundler
Version  : 1.2.0
Release  : 5
URL      : https://rubygems.org/downloads/hoe-bundler-1.2.0.gem
Source0  : https://rubygems.org/downloads/hoe-bundler-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= hoe-bundler
* http://github.com/flavorjones/hoe-bundler
== DESCRIPTION:
Generate a Gemfile based on a Hoe spec's declared dependencies.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hoe-bundler-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-hoe-bundler.gemspec

%build
gem build rubygem-hoe-bundler.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hoe-bundler-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/hoe-bundler-1.2.0
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/hoe-bundler-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/.gemtest
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/CHANGELOG.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/lib/hoe/bundler.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/test/fixture_project/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/test/fixture_project/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/test/fixture_project/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/test/fixture_project/README.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/test/fixture_project/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/test/fixture_project/lib/fixture_project.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/test/fixture_project/test/test_fixture_project.rb
/usr/lib64/ruby/gems/2.3.0/gems/hoe-bundler-1.2.0/test/test_hoe_bundler.rb
/usr/lib64/ruby/gems/2.3.0/specifications/hoe-bundler-1.2.0.gemspec
